import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import { MantineProvider, createTheme, ColorSchemeScript } from '@mantine/core';
import '@mantine/core/styles.css';

export const metadata: Metadata = {
  title: "<Shrinked Logo Placeholder>",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

const theme = createTheme({
  primaryColor: 'blue',
  colors: {
    dark: [
      '#C1C2C5',
      '#A6A7AB',
      '#909296',
      '#5c5f66',
      '#373A40',
      '#2C2E33',
      '#25262b',
      '#1A1B1E',
      '#141517',
      '#101113',
    ],
    blue: [
      '#e6f3ff',
      '#cce3ff',
      '#99c2ff',
      '#66a1ff',
      '#3380ff',
      '#005fff',
      '#0044cc',
      '#003399',
      '#002266',
      '#001133'
    ],
  },
  white: '#fff',
  black: '#1A1B1E',
  
  components: {
    Button: {
      defaultProps: {
        color: 'blue',
        variant: 'filled',
      },
      styles: {
        root: {
          backgroundColor: 'var(--mantine-color-dark-9)',
          color: 'var(--mantine-color-white)',
          '&:hover': {
            backgroundColor: 'var(--mantine-color-blue-7)',
          },
        },
      },
    },
    Paper: {
      defaultProps: {
        bg: 'dark.7',
      },
    },
    ActionIcon: {
      defaultProps: {
        color: 'blue',
      },
      styles: {
        root: {
          color: 'var(--mantine-color-white)',
        },
      },
    },
    Input: {
      styles: {
        input: {
          backgroundColor: 'var(--mantine-color-dark-7)',
          color: 'var(--mantine-color-white)',
          borderColor: 'var(--mantine-color-dark-4)',
          '&:focus': {
            borderColor: 'var(--mantine-color-blue-6)',
          },
        },
      },
    },
    Table: {
      styles: {
        root: {
          backgroundColor: 'var(--mantine-color-dark-7)',
          color: 'var(--mantine-color-white)',
        },
        th: {
          backgroundColor: 'var(--mantine-color-dark-6)',
          color: 'var(--mantine-color-white)',
        },
        td: {
          color: 'var(--mantine-color-white)',
        },
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mantine-color-scheme="dark">
      <head>
        <ColorSchemeScript forceColorScheme="dark" />
        <meta name="color-scheme" content="dark" />
      </head>
      <body style={{ backgroundColor: '#1A1B1E', color: '#fff' }}>
        <MantineProvider 
          theme={theme} 
          forceColorScheme="dark"
        >
          <Suspense>
            <RefineContext>{children}</RefineContext>
          </Suspense>
        </MantineProvider>
      </body>
    </html>
  );
}
