import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import { MantineProvider, createTheme } from '@mantine/core';
import '@mantine/core/styles.css';

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

const theme = createTheme({
  primaryColor: 'blue',
  // Color scheme
  colors: {
    dark: [
      '#C1C2C5', // Text color
      '#A6A7AB',
      '#909296',
      '#5c5f66',
      '#373A40',
      '#2C2E33',
      '#25262b',
      '#1A1B1E',
      '#141517',
      '#101113',
    ],
    blue: [
      '#e6f3ff',
      '#cce3ff',
      '#99c2ff',
      '#66a1ff',
      '#3380ff',
      '#005fff',
      '#0044cc',
      '#003399',
      '#002266',
      '#001133'
    ],
  },
  white: '#fff',
  black: '#1A1B1E',
  
  // Component specific themes
  components: {
    Button: {
      defaultProps: {
        color: 'blue',
        variant: 'filled',
      },
      styles: (theme) => ({
        root: {
          backgroundColor: theme.colors.blue[6],
          color: theme.white,
          '&:hover': {
            backgroundColor: theme.colors.blue[7],
          },
        },
      }),
    },
    Paper: {
      defaultProps: {
        bg: 'dark.7',
      },
    },
    ActionIcon: {
      defaultProps: {
        color: 'blue',
      },
      styles: (theme) => ({
        root: {
          color: theme.white,
        },
      }),
    },
    Input: {
      styles: (theme) => ({
        input: {
          backgroundColor: theme.colors.dark[7],
          color: theme.white,
          borderColor: theme.colors.dark[4],
          '&:focus': {
            borderColor: theme.colors.blue[6],
          },
        },
      }),
    }),
    Table: {
      styles: (theme) => ({
        root: {
          backgroundColor: theme.colors.dark[7],
          color: theme.white,
        },
        th: {
          backgroundColor: theme.colors.dark[6],
          color: theme.white,
        },
        td: {
          color: theme.white,
        },
      }),
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mantine-color-scheme="dark">
      <head>
        <ColorSchemeScript forceColorScheme="dark" />
        <meta name="color-scheme" content="dark" />
      </head>
      <body style={{ backgroundColor: '#1A1B1E', color: '#fff' }}>
        <MantineProvider 
          theme={theme} 
          forceColorScheme="dark"
        >
          <Suspense>
            <RefineContext>{children}</RefineContext>
          </Suspense>
        </MantineProvider>
      </body>
    </html>
  );
}