import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import { MantineProvider, createTheme } from '@mantine/core';
import '@mantine/core/styles.css';

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

// Create dark theme
const theme = createTheme({
  primaryColor: 'blue',
  white: '#fff',
  black: '#1a1b1e',
  defaultRadius: 'sm',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="dark" />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <Suspense>
            <RefineContext>{children}</RefineContext>
          </Suspense>
        </MantineProvider>
      </body>
    </html>
  );
}